name: lint-and-import
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
      - name: Import smoke test
        run: |
          python - <<'PY'
          import numpy as np
          print("NumPy OK")
          try:
              import numba
              print("Numba OK")
          except Exception as e:
              print("Numba import failed (acceptable on CI):", e)
          print("Smoke test passed")
          PY
